services:
  redis-7001:
    image: redis:7.2.4
    container_name: redis-7001
    restart: always
    ports:
      - "7001:7001"
      - "17001:17001"
    volumes:
      - "./7001/data:/data"
      - "./7001/conf/redis.conf:/etc/redis/redis.conf"
    command: redis-server /etc/redis/redis.conf
    networks:
      - redis_cluster
  redis-7002:
    image: redis:7.2.4
    container_name: redis-7002
    restart: always
    ports:
      - "7002:7002"
      - "17002:17002"
    volumes:
      - "./7002/data:/data"
      - "./7002/conf/redis.conf:/etc/redis/redis.conf"
    command: redis-server /etc/redis/redis.conf
    networks:
      - redis_cluster
  redis-7003:
    image: redis:7.2.4
    container_name: redis-7003
    restart: always
    ports:
      - "7003:7003"
      - "17003:17003"
    volumes:
      - "./7003/data:/data"
      - "./7003/conf/redis.conf:/etc/redis/redis.conf"
    command: redis-server /etc/redis/redis.conf
    networks:
      - redis_cluster
  redis-7004:
    image: redis:7.2.4
    container_name: redis-7004
    restart: always
    ports:
      - "7004:7004"
      - "17004:17004"
    volumes:
      - "./7004/data:/data"
      - "./7004/conf/redis.conf:/etc/redis/redis.conf"
    command: redis-server /etc/redis/redis.conf
    networks:
      - redis_cluster
  redis-7005:
    image: redis:7.2.4
    container_name: redis-7005
    restart: always
    ports:
      - "7005:7005"
      - "17005:17005"
    volumes:
      - "./7005/data:/data"
      - "./7005/conf/redis.conf:/etc/redis/redis.conf"
    command: redis-server /etc/redis/redis.conf
    networks:
      - redis_cluster
  redis-7006:
    image: redis:7.2.4
    container_name: redis-7006
    restart: always
    ports:
      - "7006:7006"
      - "17006:17006"
    volumes:
      - "./7006/data:/data"
      - "./7006/conf/redis.conf:/etc/redis/redis.conf"
    command: redis-server /etc/redis/redis.conf
    networks:
      - redis_cluster

networks:
  redis_cluster:
    driver: bridge