services:
  # 可参考： https://hub.docker.com/_/mysql
  mysql:
    image: mysql:8.4.7
    container_name: mysql
    restart: always
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_DATABASE: nacos_config
    volumes:
      - ./mysql/conf/my.cnf:/etc/mysql/my.cnf
      - ./mysql/data:/var/lib/mysql
      - ./mysql/mysql-files:/var/lib/mysql-files
      - ./mysql/init:/docker-entrypoint-initdb.d
    privileged: true
    user: root
    ports:
      - "3306:3306"
  nacos:
    image: nacos/nacos-server:v2.5.2
    container_name: nacos
    restart: always
    depends_on:
      - mysql
    environment:
      - MODE=standalone
      - PREFER_HOST_MODE=hostname
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=nacos_config
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=root@123
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      - NACOS_AUTH_ENABLE=true # 建议开启权限认证
      - NACOS_AUTH_TOKEN=bXljdXN0b21zZWNyZXRrZXlmb3JuYWNvczIwMjZ2ZXJzaW9u
      - NACOS_AUTH_IDENTITY_KEY=nacos
      - NACOS_AUTH_IDENTITY_VALUE=nacos
      - JVM_XMS=256m
      - JVM_XMX=256m
      - JVM_MS=128m
      - JVM_MMS=320m
    volumes:
      - "./nacos/data:/home/nacos/data"
      - "./nacos/logs:/home/nacos/logs"
    ports:
      - "8848:8848"
      - "9848:9848" # gRPC 客户端连接端口
      - "9849:9849" # gRPC 服务端端口
    links:
      - mysql
  xxl-job-admin:
    image: xuxueli/xxl-job-admin:2.4.1
    container_name: xxl-job-admin
    restart: always
    depends_on:
      - mysql
    environment:
      PARAMS: "--spring.datasource.url=jdbc:mysql://mysql:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
               --spring.datasource.username=root
               --spring.datasource.password=root@123
               --server.servlet.context-path=/xxl-job-admin
               --xxl.job.accessToken=Xwn8HCVs"
    volumes:
      - ./xxl-job/logs:/data/applogs
    ports:
      - "9090:8080"