services:
  redis:
    image: redis:7.2.4
    container_name: redis
    privileged: true
    restart: always
    command: redis-server /etc/redis/redis.conf
    environment:
      TZ: Asia/Shanghai
    volumes:
      - "./data:/data"
      - "./conf/redis.conf:/etc/redis/redis.conf"
    ports:
      - "6379:6379"