# 可参考： https://hub.docker.com/_/mysql
services:
  mysql:
    image: mysql:8.4.7
    container_name: mysql
    restart: always
    volumes:
      - "./conf/my.cnf:/etc/mysql/my.cnf"
      - "./data:/var/lib/mysql"
      - "./mysql-files:/var/lib/mysql-files"
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      MYSQL_ROOT_PASSWORD: root@123
    privileged: true
    user: root
    ports:
      - "3306:3306"