services:
  rmqnamesrv:
    image: apache/rocketmq:5.3.2
    container_name: rmqnamesrv
    restart: always
    ports:
      - "9876:9876"
    environment:
      JAVA_OPT_EXT: "-server -Xms256m -Xmx256m"
    volumes:
      - ./namesrv/logs:/home/rocketmq/logs
    command: sh mqnamesrv
    networks:
      rocketmq:
        aliases:
          - rmqnamesrv

  rmqbroker:
    image: apache/rocketmq:5.3.2
    container_name: rmqbroker
    depends_on:
      - rmqnamesrv
    ports:
      - "10909:10909"
      - "10911:10911"
      - "10912:10912"
    environment:
      NAMESRV_ADDR: "rmqnamesrv:9876"
      JAVA_OPT_EXT: "-server -Xms512m -Xmx512m"
    volumes:
      - ./broker/store:/home/rocketmq/store
      - ./broker/logs:/home/rocketmq/logs/rocketmqlogs
      - ./broker/conf/broker.conf:/home/rocketmq/rocketmq-5.3.2/conf/broker.conf
    command: sh mqbroker -c /home/rocketmq/rocketmq-5.3.2/conf/broker.conf --enable-proxy
    networks:
      rocketmq:
        aliases:
          - rmqbroker

  rmqconsole:
    image: apacherocketmq/rocketmq-console:2.0.0
    container_name: rmqconsole
    restart: always
    ports:
      - "19876:19876"
    environment:
      JAVA_OPTS: "-server -Xmx256m -Xms256m -Dserver.port=19876 -Drocketmq.namesrv.addr=rmqnamesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
    depends_on:
      - rmqnamesrv
    networks:
      rocketmq:
        aliases:
          - rmqconsole

networks:
  rocketmq:
    driver: bridge